#cloud-config
coreos: 
  units: 
    - name: etcd.service
      command: stop 
      mask: true
    - name: fleet.service
      command: stop
      mask: true
    - name: docker-tcp.socket
      command: start
      content: |
          [Unit]
          Description=Docker Socket for the API
          
          [Socket]
          ListenStream=2375
          Service=docker.service
          BindIPv6Only=both
          
          [Install]
          WantedBy=sockets.target
    - name: enable-docker-tcp.service 
      command: start
      content: |
          [Unit]
          Description=Enable the Docker Socket for the API
          
          [Service]
          Type=oneshot
          ExecStart=/usr/bin/systemctl enable docker-tcp.socket
  update:
    group: alpha
    reboot-strategy: off
ssh_authorized_keys:
  - "ssh-dss AAAAB3NzaC1kc3MAAACBAIquBtpC//6PWJREGliFbNjLQTUnDdcuM60HhWubJgO26ODQXqQHqA060tRCBiiR4Sr8UsFoTVfsJvLFUkqXLq3i6aQa14u7Muae7F1ZrYrb0RvCG6XLXEq+TQf2rQoq4AiCg8Jbs3nzKqRHSGOE0FDlELoOn8UKhTv4lr489zOBAAAAFQDXgXBxN2Om9qBRdhLkVXXNmoQPGQAAAIBGA5DFoLBTLrwGdH2ABtGT7F3G6i2TPWUs3aHWRjCtG6UCGWiLBy6/tGsN/5IhYKbLIC3mUTl3c/Oxc4sMmlQ2NhcHe0VOfz5oElzChf7ruxJzA9vxBtEABx0Gs3EIMpWsQuNeSq091mljX+00Ie56Ey5pX7RbQCneprZmDDlsHgAAAIA8LZHLQfG+5WKRq3B0+O2U1V5GdxCe6/BYxgqV5Go/cdpkN7H7tY4YkvEm0EI/i4GqJuo1LpOQZZOcr2RhrZsACU5Ic3npLQfwox8frEcz2DWv7IdxWhezGZiXmUnor9ohYNlNGTmV613YXP0AJERJVbV/nkmzyzZqE2KewIdMSQ== amarshall@Austins-MacBook-Pro-3.local"
